### PR TITLE
Add Dockerfile, docker-compose.yml and some info

### PR DESCRIPTION
**Pull request by theodorosploumis**
I think it would be nice to have these files on the repo too! Thanks for the example.

### CODE REVIEW

**Comment by retrohacker** [comment]
Hey @theodorosploumis!

These files look great, thank you for opening this PR!

Part of me says that a big portion of the tutorial is actually creating those files and getting familiar with the syntax...

The other part says that people need a reference solution for when their file isn't working and they don't know why...

Perhaps we can get the best of both worlds? What are your thoughts on creating a directory called `solution` and moving these files there?

**Comment by theodorosploumis** [comment]
Or maybe create a separated branch with the solutions included.

**Comment by retrohacker** [comment]
Hmm... Would a branch be as easy to find as a folder?

**Comment by retrohacker** [comment]
The branch would probably be cleaner but might be harder to find.

If we included a `solutions` directory, we would probably need to include a `.dockerignore` file as well.

**Comment by theodorosploumis** [comment]
Most of the examples of that type (git repos) have separated branches and a declaration on the readme about using other branches. Users are to lean docker they know how to use Github. Also, if we use another folder we need to copy again all the files inside the folder.

**Comment by theodorosploumis** [comment]
Also, if there is no complete setup users will not be able to propose changes, improvements (like mine) and reuse/extend the code to their needs.

**Comment by retrohacker** [comment]
This landed in the solutions branch of this repo. Instructions were added to the readme directing users to that branch.

Thanks for the contribution!

**Pull request closed without merging**
